### ISSUE TITLE
UnicodeDecodeError on startup

### ISSUE THREAD

**Issue by gretel** [zyx1121/findmy-api#1]
```shell
$ poetry run uvicorn findmy_api.main:app --host 127.0.0.1 --port 8000 --reload
INFO:     Will watch for changes in these directories: ['/Users/tom/Sync/code/findmy-api']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [22865] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/.virtualenvs/findmy-api/lib/python3.13/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/tom/.virtualenvs/findmy-api/lib/python3.13/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/tom/.virtualenvs/findmy-api/lib/python3.13/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/tom/.virtualenvs/findmy-api/lib/python3.13/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "/Users/tom/.virtualenvs/findmy-api/lib/python3.13/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/tom/.virtualenvs/findmy-api/lib/python3.13/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/tom/Sync/code/findmy-api/findmy_api/main.py", line 9, in <module>
    findmy = FindMyItem()
  File "/Users/tom/Sync/code/findmy-api/findmy_api/services.py", line 18, in __init__
    self._load_data()
    ~~~~~~~~~~~~~~~^^
  File "/Users/tom/Sync/code/findmy-api/findmy_api/services.py", line 24, in _load_data
    self.raw_data = json.load(f)
                    ~~~~~~~~~^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ~~~~~~~^^
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 8: invalid continuation byte
```

script is still running, but requests at `127.0.0.1` don't get processed. regards

**Comment by zyx1121** [comment]
I believe this is related to macOS system versions.

up until **macOS 14.3** you could still view the contents of ~/Library/Caches/com.apple.findmy.fmipcore/Items.data in **plain text**.

however starting from **macOS 14.4** Apple has now **encrypted** this file.

**normal access on macOS 13.5:**

<img width="1651" alt="macos13 5" src="https://github.com/user-attachments/assets/61f6dacc-6c6d-4d62-b310-c44825ddfee5" />

**encrypted file on macOS 15.2:**

<img width="1651" alt="macos15 2" src="https://github.com/user-attachments/assets/33a742f2-4464-4256-ae95-ff5491fae0e1" />

- https://forums.developer.apple.com/forums/thread/742555
- https://stackoverflow.com/questions/71241711/is-there-a-way-to-access-your-own-airtag-data-via-api

**Comment by gretel** [comment]
> I believe this is related to macOS system versions.
> 
> up until **macOS 14.3** you could still view the contents of ~/Library/Caches/com.apple.findmy.fmipcore/Items.data in **plain text**.
> 
> however starting from **macOS 14.4** Apple has now **encrypted** this file.
> 
> **normal access on macOS 13.5:**
> <img alt="macos13 5" width="1651" src="https://private-user-images.githubusercontent.com/98001197/396705948-61f6dacc-6c6d-4d62-b310-c44825ddfee5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDc0MjYsIm5iZiI6MTczNDU0NzEyNiwicGF0aCI6Ii85ODAwMTE5Ny8zOTY3MDU5NDgtNjFmNmRhY2MtNmM2ZC00ZDYyLWIzMTAtYzQ0ODI1ZGRmZWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDE4Mzg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OGMyY2VjNmYxZmZlMWU3MmNlNmQ5MTFlZWFhMjlmOTQ0YmU1ZmJmNWNhNTQxMWYwZjAwMmNkNDg0MWZmOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dl3t-vnUU69Mupfvt8XN2Prpw5Nv-oNTs67nGN8Aa9g">
> 
> **encrypted file on macOS 15.2:**
> <img alt="macos15 2" width="1651" src="https://private-user-images.githubusercontent.com/98001197/396706028-33a742f2-4464-4256-ae95-ff5491fae0e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDc0MjYsIm5iZiI6MTczNDU0NzEyNiwicGF0aCI6Ii85ODAwMTE5Ny8zOTY3MDYwMjgtMzNhNzQyZjItNDQ2NC00MjU2LWFlOTUtZmY1NDkxZmFlMGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDE4Mzg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxM2I3Y2ZmYWFhNjE0MzYxMjBkZDljODliMzk3NDBiZjY5M2MxYmU3M2RlYTAxYThkNDFjZjQ1ODFlZmYzNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XO85wdozkQNK2GF8uhUKrgqHIgkrhwzJqlOtwNXICdM">
> 
>     * https://forums.developer.apple.com/forums/thread/742555
> 
>     * https://stackoverflow.com/questions/71241711/is-there-a-way-to-access-your-own-airtag-data-via-api

thank you. duh, running 15.2. maybe catch `UnicodeDecodeError`? regards
